/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CarColorDto } from './carColorDto';
import { CarOrderStatusDto } from './carOrderStatusDto';


export interface CarColorOrderDto { 
    carColorOrderId?: string;
    carColor?: CarColorDto;
    orderStatus?: CarOrderStatusDto;
}

