/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CarEngineDto } from './carEngineDto';
import { CarOrderStatusDto } from './carOrderStatusDto';


export interface CarEngineOrderDto { 
    carEngineOrderId?: string;
    carEngine?: CarEngineDto;
    orderStatus?: CarOrderStatusDto;
}

