/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CarRimDto } from './carRimDto';
import { CarOrderStatusDto } from './carOrderStatusDto';


export interface CarRimOrderDto { 
    carRimOrderId?: string;
    carRim?: CarRimDto;
    orderStatus?: CarOrderStatusDto;
}

