/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseDto { 
    text?: string;
    status?: ResponseDto.StatusEnum;
    errorMessage?: string;
}
export namespace ResponseDto {
    export const StatusEnum = {
        Success: 'SUCCESS',
        Error: 'ERROR',
        Canceled: 'CANCELED',
        Failure: 'FAILURE'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


