/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SpecialEquipmentDto } from './specialEquipmentDto';
import { CarOrderStatusDto } from './carOrderStatusDto';


export interface SpecialEquipmentOrderDto { 
    specialEquipmentOrderId?: string;
    specialEquipment?: SpecialEquipmentDto;
    orderStatus?: CarOrderStatusDto;
}

