/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SpecialEquipmentDto { 
    equipmentName?: string;
    description?: string;
    productId?: string;
    categoryType?: SpecialEquipmentDto.CategoryTypeEnum;
    equipmentLocation?: SpecialEquipmentDto.EquipmentLocationEnum;
    price?: number;
}
export namespace SpecialEquipmentDto {
    export const CategoryTypeEnum = {
        Multimedia: 'MULTIMEDIA',
        Seats: 'SEATS',
        Heating: 'HEATING',
        AirCondition: 'AIR_CONDITION',
        NavigationSystem: 'NAVIGATION_SYSTEM',
        SteeringWheel: 'STEERING_WHEEL',
        Misc: 'MISC'
    } as const;
    export type CategoryTypeEnum = typeof CategoryTypeEnum[keyof typeof CategoryTypeEnum];
    export const EquipmentLocationEnum = {
        Interior: 'INTERIOR',
        Exterior: 'EXTERIOR'
    } as const;
    export type EquipmentLocationEnum = typeof EquipmentLocationEnum[keyof typeof EquipmentLocationEnum];
}


