# For more help, visit the Docker Compose reference guide:
# https://docs.docker.com/compose/compose-file/
services:
  server:
    # The name for the container, making it easier to reference from the command line.
    container_name: carconfig-app
    build:
      context: .
    environment:
      # This is the runtime environment variable for your Angular app.
      # The entrypoint.sh script will use this value.
      API_URL: http://localhost:8080/
    ports:
      - 8080:8080
    # A healthcheck tells Docker that your application is ready to accept traffic.
    # This is crucial for orchestrating multiple services that depend on each other.
    healthcheck:
      # The test command curls the local Nginx server inside the container.
      # It expects a successful HTTP response (2xx or 3xx).
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
