export * from './carColorWebController.service';
import { CarColorWebControllerService } from './carColorWebController.service';
export * from './carEngineWebController.service';
import { CarEngineWebControllerService } from './carEngineWebController.service';
export * from './carRimsWebController.service';
import { CarRimsWebControllerService } from './carRimsWebController.service';
export * from './configWebController.service';
import { ConfigWebControllerService } from './configWebController.service';
export * from './orderController.service';
import { OrderControllerService } from './orderController.service';
export * from './specialEquipmentWebController.service';
import { SpecialEquipmentWebControllerService } from './specialEquipmentWebController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export const APIS = [CarColorWebControllerService, CarEngineWebControllerService, CarRimsWebControllerService, ConfigWebControllerService, OrderControllerService, SpecialEquipmentWebControllerService, UserControllerService];
