/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderStatusDto } from './orderStatusDto';
import { CarColorDto } from './carColorDto';


export interface CarColorOrderDto { 
    carColorDto?: CarColorDto;
    orderStatusDto?: OrderStatusDto;
}

