/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CarColorDto { 
    colorName?: string;
    description?: string;
    productId?: string;
    price?: number;
    materialType?: CarColorDto.MaterialTypeEnum;
    paintingType?: CarColorDto.PaintingTypeEnum;
    colorCodeHex?: string;
}
export namespace CarColorDto {
    export const MaterialTypeEnum = {
        Matte: 'MATTE',
        Glossy: 'GLOSSY'
    } as const;
    export type MaterialTypeEnum = typeof MaterialTypeEnum[keyof typeof MaterialTypeEnum];
    export const PaintingTypeEnum = {
        Base: 'BASE',
        Special: 'SPECIAL',
        Premium: 'PREMIUM'
    } as const;
    export type PaintingTypeEnum = typeof PaintingTypeEnum[keyof typeof PaintingTypeEnum];
}


