/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CarOrderUpdateDto { 
    carOrderId?: string;
    userMail?: string;
    carEngineProductId?: string;
    carRimsProductId?: string;
    carColorProductId?: string;
    price?: number;
    specialEquipmentProductIds?: Array<string>;
}

