/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CarOrderStatusDto { 
    orderStatus?: CarOrderStatusDto.OrderStatusEnum;
    shippingDate?: string;
    deliveryDate?: string;
}
export namespace CarOrderStatusDto {
    export const OrderStatusEnum = {
        Received: 'RECEIVED',
        Pending: 'PENDING',
        Cancelled: 'CANCELLED',
        InProgress: 'IN_PROGRESS',
        Completed: 'COMPLETED'
    } as const;
    export type OrderStatusEnum = typeof OrderStatusEnum[keyof typeof OrderStatusEnum];
}


