/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CarEngineOrderDto } from './carEngineOrderDto';
import { OrderUserDto } from './orderUserDto';
import { SpecialEquipmentOrderDto } from './specialEquipmentOrderDto';
import { CarOrderStatusDto } from './carOrderStatusDto';
import { CarColorOrderDto } from './carColorOrderDto';
import { CarRimOrderDto } from './carRimOrderDto';


export interface CarOrderDto { 
    carOrderId?: string;
    orderUser?: OrderUserDto;
    carEngineOrder?: CarEngineOrderDto;
    carRimOrder?: CarRimOrderDto;
    carColorOrder?: CarColorOrderDto;
    orderStatus?: CarOrderStatusDto;
    description?: string;
    totalPrice?: number;
    specialEquipmentOrders?: Array<SpecialEquipmentOrderDto>;
    createdAt?: string;
    updatedAt?: string;
}

