/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CarEngineOrderDto } from './carEngineOrderDto';
import { OrderUserDto } from './orderUserDto';
import { SpecialEquipmentOrderDto } from './specialEquipmentOrderDto';
import { OrderStatusDto } from './orderStatusDto';
import { CarColorOrderDto } from './carColorOrderDto';
import { CarRimOrderDto } from './carRimOrderDto';


export interface OrderDto { 
    orderId?: string;
    orderUser?: OrderUserDto;
    carEngineOrder?: CarEngineOrderDto;
    carRimOrder?: CarRimOrderDto;
    carColorOrder?: CarColorOrderDto;
    orderStatus?: OrderStatusDto;
    description?: string;
    price?: number;
    specialEquipmentOrders?: Array<SpecialEquipmentOrderDto>;
}

