/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SpecialEquipmentDto } from './specialEquipmentDto';
import { OrderStatusDto } from './orderStatusDto';


export interface SpecialEquipmentOrderDto { 
    specialEquipmentDto?: SpecialEquipmentDto;
    orderStatusDto?: OrderStatusDto;
}

