/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SpecialEquipmentDto { 
    name?: string;
    model?: string;
    description?: string;
    productId?: string;
    price?: number;
}

